# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('email', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=30)),
                ('project_client', models.CharField(max_length=25)),
                ('project_details', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='projectEmployee',
            fields=[
                ('projectEmployee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=25)),
                ('porject_employee', models.CharField(max_length=25, null=True)),
                ('project_TL', models.CharField(max_length=25, null=True)),
                ('project_manager', models.CharField(max_length=25)),
            ],
        ),
    ]
